mod_blog/models.py
from app import db

post_category = db.Table('posts_categories', db.metadata,
                         db.Column('category_id', db.Integer(), db.ForeignKey(
                             'categories.id', ondelete='CASCADE')),
                         db.Column('post_id', db.Integer(), db.ForeignKey(
                             'posts.id', ondelete='CASCADE'))
                         )


class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(128), nullable=False, unique=True)
    description = db.Column(db.Text())
    slug = db.Column(db.String(64), nullable=False, unique=True)
    posts = db.relationship(
        "Post", secondary=post_category, backref=db.backref("categories", lazy="dynamic"), lazy="dynamic"
    )


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(128), nullable=False, unique=True)
    summary = db.Column(db.Text())
    content = db.Column(db.Text(),nullable=False)
    slug = db.Column(db.String(64), nullable=False, unique=True)

mod_blog/forms.py
from flask_wtf import FlaskForm
from sqlalchemy import and_
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import DataRequired,ValidationError
import re
from .models import Post,Category
from .utils.form import MultipleCheckBoxField

class CreatePostForm(FlaskForm):
    title = StringField(label="Post title",validators=[DataRequired()])
    summary = TextAreaField(label="Post summary")
    content = TextAreaField(label="Post content",validators=[DataRequired()])
    slug = StringField(label="Post slug",validators=[DataRequired()])
    categories_ = MultipleCheckBoxField(label="Categories",choices=[],coerce=int)
    submit = SubmitField(label="Create post")

    def validate_title(self,title):
        post = Post.query.filter(Post.title == self.title.data).first()
        if post : 
            raise ValidationError("Title dupplicated . Try another title .")

    def validate_slug(self,slug):
        post = Post.query.filter(Post.slug == self.slug.data).first()
        if post : 
            raise ValidationError("Slug dupplicated . Try another slug .")
        if not re.search("^[a-z0-9]+(?:-[a-z0-9]+)*$", str(self.slug.data)):
            raise ValidationError("Invalid slug pattern")

class ModifyPostForm(FlaskForm):
    title = StringField(label="Post title",validators=[DataRequired()])
    summary = TextAreaField(label="Post summary")
    content = TextAreaField(label="Post content",validators=[DataRequired()])
    slug = StringField(label="Post slug",validators=[DataRequired()])
    categories_ = MultipleCheckBoxField(label="Categories",choices=[],coerce=int)
    submit = SubmitField(label="Modify post")

    def set_post_id(self,post_id):
        self.post_id = post_id
    
    def validate_title(self,title):
        post = Post.query.filter(and_(Post.title == self.title.data, Post.id != self.post_id)).first()
        if post : 
            raise ValidationError("Title dupplicated . Try another title .")

    def validate_slug(self,slug):
        post = Post.query.filter(and_(Post.slug == self.slug.data, Post.id != self.post_id)).first()
        if post : 
            raise ValidationError("Slug dupplicated . Try another slug .")
        if not re.search("^[a-z0-9]+(?:-[a-z0-9]+)*$", str(self.slug.data)):
            raise ValidationError("Invalid slug pattern")

class CreateCategoryForm(FlaskForm):
    name = StringField(label="Category name",validators=[DataRequired()])
    description = TextAreaField(label="Category description")
    slug = StringField(label="Category slug",validators=[DataRequired()])
    submit = SubmitField(label="Create category")

    def validate_name(self,name):
        category = Category.query.filter(Category.name == self.name.data).first()
        if category :
            raise ValidationError("Category name dupplicated . Try another name .")

    def validate_slug(self,slug):
        category = Category.query.filter(Category.slug == self.slug.data).first()
        if category:
            raise ValidationError("Slug dupplicated . Try another slug .")
        if not re.search("^[a-z0-9]+(?:-[a-z0-9]+)*$", str(self.slug.data)):
            raise ValidationError("Invalid slug pattern")

class ModifyCategoryForm(FlaskForm):
    name = StringField(label="Category name",validators=[DataRequired()])
    description = TextAreaField(label="Category description")
    slug = StringField(label="Category slug",validators=[DataRequired()])
    submit = SubmitField(label="Modify category")

    def set_category_id(self,category_id):
        self.category_id = category_id

    def validate_name(self,name):
        category = Category.query.filter(and_(Category.name == self.name.data, Category.id != self.category_id)).first()
        if category :
            raise ValidationError("Category name dupplicated . Try another name .")

    def validate_slug(self,slug):
        category = Category.query.filter(and_(Category.slug == self.slug.data, Category.id != self.category_id)).first()
        if category:
            raise ValidationError("Slug dupplicated . Try another slug .")
        if not re.search("^[a-z0-9]+(?:-[a-z0-9]+)*$", str(self.slug.data)):
            raise ValidationError("Invalid slug pattern")

class SearchForm(FlaskForm):
    search = StringField(label='Serach',validators=[DataRequired()])
    submit = SubmitField(label="Search")

mod_blog/__init__.py
from flask import Blueprint

blog = Blueprint('blog',__name__,url_prefix="/blog",template_folder='templates')

from . import models,views

mod_blog/views.py
from flask import render_template,request
from sqlalchemy import or_
from . import blog
from .models import Category, Post

@blog.route('/')
def index():
    posts = Post.query.all()
    return render_template('blog/index.html',posts=posts)

@blog.route('/<string:slug>')
def single_post(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    return render_template('blog/single_post.html',post=post,title=post.title)

@blog.route('/search')
def search_blog():
    search_query = request.args.get('search',default='')
    
    title_cond = Post.title.ilike(f'%{search_query}%')
    summay_cond = Post.summary.ilike(f'%{search_query}%')    
    content_cond = Post.content.ilike(f'%{search_query}%')
    found_post = Post.query.filter(or_(title_cond,summay_cond,content_cond)).all()
    
    return render_template('blog/search_post.html',posts=found_post,search=search_query,title=f'Search for \'{search_query}\'')

@blog.route('/category/<string:slug>')
def single_category(slug):
    category = Category.query.filter(Category.slug == slug).first_or_404()
    return render_template('blog/single_category.html',posts=category.posts,title=f'Category \'{category.name}',category=category)

mod_blog/templates/blog/_navbar.html
{% if session.get('user_role')==1 %}
{% include 'admin/_navbar.html' %}
{% else %}
{% include 'user/_navbar.html' %}
{% endif %}

mod_blog/templates/blog/base.html
{% extends 'base.html' %}

{% block content %}

{% include 'blog/_navbar.html' %}

{% block page_content %}
{% endblock %}

{% endblock %}

mod_blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% from 'blog/macros.html' import post_card %}

{% block page_content %}
<div class="container">
    <h1 class="my-3">Blog page</h1>
    {% if posts %}
        {% for post in posts %}
            {{ post_card(post) }} <br>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

mod_blog/templates/blog/macros.html
{% macro post_card(post) %}
<div class="card">
    <div class="card-body">
      <h5 class="card-title"><a class="text-decoration-none" href="{{ url_for('blog.single_post',slug=post.slug) }}">{{ post.title }}</a></h5>
      <p class="card-text">{{ post.summary or post.content|striptags()|truncate(64,false,' ... ') }}</p>
      <a href="{{ url_for('blog.single_post',slug=post.slug) }}" class="btn btn-primary">Show Post</a>
    </div>
</div>
{% endmacro %}

mod_blog/templates/blog/search_post.html
{% extends 'blog/base.html' %}
{% from 'blog/macros.html' import post_card %}

{% block page_content %}
<div class="container">
    <h1 class="my-3">Search for '{{ search }}'</h1>
    {% if posts %}
        {% for post in posts %}
            {{ post_card(post) }} <br>
        {% endfor %}
    {% else %}
    <h3>No post found</h3>    
    {% endif %}

</div>
{% endblock %}

mod_blog/templates/blog/single_category.html
{% extends 'blog/base.html' %}
{% from 'blog/macros.html' import post_card %}

{% block page_content %}
<div class="container">
    <h1 class="my-3">Category '{{ category.name }}'</h1>
    {% if posts %}
        {% for post in posts %}
            {{ post_card(post) }} <br>
        {% endfor %}
    {% else %}
    <h3>No post found</h3>    
    {% endif %}

</div>
{% endblock %}

mod_blog/templates/blog/single_post.html
{% extends 'blog/index.html' %}

{% block page_content %}
<div class="container">
    <h1>{{ post.title }}</h1>
    <p class="lead">{{ post.content|safe() }}</p>
</div>
{% endblock %}